image: docker.adeo.no:5000/fo/veilarbvisittkortfs
replicas:
  min: 1
  max: 2
  cpuThresholdPercentage: 50
port: 80
healthcheck:
  liveness:
    path: isAlive
    initialDelay: 10
  readiness:
    path: isReady
    initialDelay: 10
fasitResources:
  used:
  - alias: loadbalancer:veilarbvisittkortfs
    resourceType: loadbalancerconfig
team: biff
alertProfiles:
- minimal
