apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbvisittkortfs
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbvisittkortfs/veilarbvisittkortfs:{{version}}
  port: 80
  liveness:
    path: /veilarbvisittkortfs/isAlive
    initialDelay: 10
  readiness:
    path: /veilarbvisittkortfs/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  ingresses:
    - https://veilarbvisittkortfs.nais.adeo.no
    - https://app.adeo.no/veilarbvisittkortfs
